# Project-wide Gradle settings.
# For more details on how to configure your build, see
# http://www.gradle.org/docs/current/userguide/build_logic.html
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For example, to set the JVM memory to 2048 MB:
# org.gradle.jvmargs=-Xmx2048m

android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true
